/*
 * $Id: addaptive_stats.h,v 1.1.1.1 2000/08/28 21:11:38 slumos Exp $
 *
 * Statistical Spell Checker Prototype
 * Eric Stofsky
 * file: addaptive_stats.h (learning statistical adjustment header)
*/


/* Ocrspell OCR-based statistical spell checker
 * Copyright (C) 1995 Regents of the University of Nevada
 * Text Retrieval Group
 * Information Science Research Institute
 * University of Nevada, Las Vegas
 * Las Vegas, NV 89154-4021
 * isri-text@isri.unlv.edu.
 *
*/


/* 
 * change the following constants to increase the rate
 * at which the learning mode's statistics effect the
 * choices generated by OCRSpell
 */


#define ADDAPT_INCREMENT 1.0
#define ADDAPT_DECREMENT 1.0

void addaptive_stats_update(int);
void addaptive_stringmatch_decrement(int, int);
void addaptive_file_dump(char *, int);


